### PR TITLE
Updated the SMACK tool wrapper

### PR DESCRIPTION
**Pull request by shaobo-he**

### CODE REVIEW

**Comment by shaobo-he** [comment]
@PhilippWendler Could you share some pointers about testing these changes? Do I need to install benchexec or I can write some dummy programs to test them?

**Comment by PhilippWendler** [comment]
Our documentation for this is [here](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md), please let me know if you find anything missing or have further questions. There is a [test utility](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md#testing-the-tool-integration) that one should use, it requires at least a git checkout of BenchExec (not a full installation if you for example use `PYTHONPATH`  or so for letting your Python know about the BenchExec checkout).

Please also have a look at the CI results.

From your question, I assume that this is still work in progress, so I will mark the PR as draft. Please comment once you are ready for a review.

**Comment by PhilippWendler** [comment]
@shaobo-he @zvonimir Is this relevant for this year's SV-COMP or do you just want to add further improvements to the tool-info module that can also be merged later?

**Comment by zvonimir** [comment]
Sorry, this is not for this year but improvements for future incarnations.

**Comment by PhilippWendler** [comment]
No problem, I just wanted to ask for clarification such that nothing gets forgotten.

**Comment by zvonimir** [comment]
Yep, I get it, we should have been more clear about the fact this was not for this year's SVCOMP. Thanks!

**Comment by PhilippWendler** [comment]
Are you still interested in getting this merged? Otherwise I will close it.

**Comment by zvonimir** [comment]
@shaobo-he Could you please comment on this one?
Maybe you remember what this was about :). Thanks!

**Comment by shaobo-he** [comment]
> Are you still interested in getting this merged? Otherwise I will close it.

Sorry for the late reply. Please close it. We'll submit a new PR if have something new. Thank you.

**Pull request closed without merging**
