### PR TITLE
New violation witness checker using concrete execution

### PR DESCRIPTION
**Pull request by tautschnig**
Witness checker currently in review:
https://github.com/diffblue/cprover-sv-comp/pull/14

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Is there a specific reason why this class does not inherit from `benchexec.tools.template.BaseTool` like all the other classes, and instead duplicates a lot of the code?

**Comment by tautschnig** [comment]
No, it's just me not being a Python guru and trying to build a best-of of cbmc.py and template.py. I'll review and update. Thanks a lot for the immediate feedback!!!

**Comment by tautschnig** [comment]
My apologies for the messy first version, hopefully this one is more acceptable!

**Comment by PhilippWendler** [comment]
Much better, thanks.

**Pull request merged**
