### PR TITLE
CLI for pqos added

### PR DESCRIPTION
**Pull request by alohamora**
An inital version for CLI for pqos library is added.
Currently the CLI allows the user to check support of OS and kernel interface in their interface

### CODE REVIEW

**Comment by alohamora** [comment]
> I wonder if it makes sense to have this wrapper in the BenchExec repository, or if we should create a separate project (like we did for cpu-energy-meter)?

Yes, I also think that using a different repository would be different as it is a completely different CLI.
Shall I create a new repository by the name `pqos-wrapper`? 
Or can you suggest a better name for the same.   
> 
> Could you please add a license to the source files? Is Apache 2.0 ok for you?

Yes, I shall add the Apache 2.0 license to the source files

**Comment by PhilippWendler** [comment]
> > I wonder if it makes sense to have this wrapper in the BenchExec repository, or if we should create a separate project (like we did for cpu-energy-meter)?
> 
> Yes, I also think that using a different repository would be different as it is a completely different CLI.
> Shall I create a new repository by the name `pqos-wrapper`?
> Or can you suggest a better name for the same.

The name is fine. I suggest I create the repo such that it is under the `sosy-lab` org. But if you agree, I would create it on GitLab, because I find GitLab more powerful and with much better CI.

**Comment by alohamora** [comment]
Sure, we can use Gitlab for the project.

**Comment by PhilippWendler** [comment]
Moved to https://gitlab.com/sosy-lab/software/pqos-wrapper

**Pull request closed without merging**
