### PR TITLE
Fix position of close button in select columns view

### PR DESCRIPTION
**Pull request by marto97**
Hi @PhilippWendler 

I copied the solution for X close button from `LinkOverlay.js`.

I updated dependencies with `npm update` and `npx browserslist@latest --update-db`  because when I run `npm run build` I get error: `Browserslist: caniuse-lite is outdated. Please run next command npm update`. Now it seems everything is okay.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
The message about `Browserslist` is just a warning, you can safely ignore it. And anyway we would need to do it in a separate commit.

Could you please provide a commit with only the desired change (which I think looks good)? Probably the easiest way is `git reset --hard origin/master`, redo the change, and `git push --force`.

**Comment by marto97** [comment]
Okay I will push a separate commit with only the desired change.

**Comment by marto97** [comment]
@PhilippWendler last commit have `package-lock.json` and  `package.json` reverted as in `master` branch.

**Comment by PhilippWendler** [comment]
But the bundles have not changed, so they still contain the updated libraries.

**Comment by marto97** [comment]
Oh sorry, I will fix it now.

**Pull request merged**
