### PR TITLE
Add support for DIVINE 4

### PR DESCRIPTION
**Pull request by vlstill**
I would like to add support for DIVINE 4 to benchexec as we will participate in SV-COMP.

### CODE REVIEW

**Comment by vlstill** [comment]
Not really, if it is desirable to keep functionality with old archives, I would prefer to split the two drivers (i.e. keeping the old one and add a new for DIVINE 4) as I am doubtful even the version detection would work on both versions.

**Comment by PhilippWendler** [comment]
This would also be ok. You could name it `divine4` for example. You can also use inheritance between the tool-info modules to reuse code that is still the same, if it is worthwhile (several modules for Ultimate and CProver do this, for example).

**Comment by vlstill** [comment]
OK, I have moved the new module to `divine4`.

**Comment by dbeyer** [comment]
@vlstill:
`python3 -m benchexec.test_tool_in
fo benchexec.tools.divine4`
yields
```
Name of tool module: “benchexec.tools.divine4”
[...]
WARNING: Determining version failed:
Traceback (most recent call last):
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/test_tool_info.py", line 79, in print_tool_info
    print_value('Version', tool.version(executable))
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/tools/divine4.py", line 65, in version
    logging.warning('Cannot determine {0} version, exit code {1}'.
NameError: name 'logging' is not defined
Working directory: “.”
```
Could you please fix this?

**Comment by dbeyer** [comment]
@vlstill:
`python3 -m benchexec.test_tool_in
fo benchexec.tools.divine4`
yields
```
Name of tool module: “benchexec.tools.divine4”
[...]
WARNING: Determining version failed:
Traceback (most recent call last):
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/test_tool_info.py", line 79, in print_tool_info
    print_value('Version', tool.version(executable))
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/tools/divine4.py", line 65, in version
    logging.warning('Cannot determine {0} version, exit code {1}'.
NameError: name 'logging' is not defined
Working directory: “.”
```
Could you please fix this?

**Comment by dbeyer** [comment]
@vlstill:
`python3 -m benchexec.test_tool_in
fo benchexec.tools.divine4`
yields
```
Name of tool module: “benchexec.tools.divine4”
[...]
WARNING: Determining version failed:
Traceback (most recent call last):
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/test_tool_info.py", line 79, in print_tool_info
    print_value('Version', tool.version(executable))
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/tools/divine4.py", line 65, in version
    logging.warning('Cannot determine {0} version, exit code {1}'.
NameError: name 'logging' is not defined
Working directory: “.”
```

**Comment by dbeyer** [comment]
@vlstill:
`python3 -m benchexec.test_tool_in
fo benchexec.tools.divine4`
yields
```
Name of tool module: “benchexec.tools.divine4”
[...]
WARNING: Determining version failed:
Traceback (most recent call last):
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/test_tool_info.py", line 79, in print_tool_info
    print_value('Version', tool.version(executable))
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/tools/divine4.py", line 65, in version
    logging.warning('Cannot determine {0} version, exit code {1}'.
NameError: name 'logging' is not defined
Working directory: “.”
```

**Comment by dbeyer** [comment]
@vlstill:
`python3 -m benchexec.test_tool_in
fo benchexec.tools.divine4`
yields
```
Name of tool module: “benchexec.tools.divine4”
[...]
WARNING: Determining version failed:
Traceback (most recent call last):
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/test_tool_info.py", line 79, in print_tool_info
    print_value('Version', tool.version(executable))
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/tools/divine4.py", line 65, in version
    logging.warning('Cannot determine {0} version, exit code {1}'.
NameError: name 'logging' is not defined
Working directory: “.”
```

**Comment by dbeyer** [comment]
@vlstill:
`python3 -m benchexec.test_tool_in
fo benchexec.tools.divine4`
yields
```
Name of tool module: “benchexec.tools.divine4”
[...]
WARNING: Determining version failed:
Traceback (most recent call last):
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/test_tool_info.py", line 79, in print_tool_info
    print_value('Version', tool.version(executable))
  File "/localhome/dbeyer/RC-checkouts/benchexec/benchexec/tools/divine4.py", line 65, in version
    logging.warning('Cannot determine {0} version, exit code {1}'.
NameError: name 'logging' is not defined
Working directory: “.”
```

**Comment by dbeyer** [comment]
Sorry in case you received many notifications, I added and removed and readded a comment several times, due to a temporary problem that GitHub was experiencing.

**Comment by dbeyer** [comment]
In the meanwhile, I fixed this with commit 95fd55e,
but now I get
`WARNING: Cannot determine ./divine version, exit code 127`
when the tool-info-module tries to compute the version string.

**Comment by vlstill** [comment]
I am sorry for my late reply. Sadly I am not able to reproduce this problem (using `benchexec` master, our verification submission and our faculty's machine with Ubuntu 18.04:
```
$ python3 -m benchexec.test_tool_info benchexec.tools.divine4
Name of tool module: “benchexec.tools.divine4”
Full name of tool module: “benchexec.tools.divine4”
Name of tool: “DIVINE”
Executable: “./divine”
Executable (absolute path): “/home/xstill/divine-svc/divine”
Version: “ 4.1.16+10a8a30b4db6”
…
```

Could you please paste here the output of `divine --version`? Sorry for the complications.

**Comment by vlstill** [comment]
I am sorry for my late reply. Sadly I am not able to reproduce this problem (using `benchexec` master, our verification submission and our faculty's machine with Ubuntu 18.04:
```
$ python3 -m benchexec.test_tool_info benchexec.tools.divine4
Name of tool module: “benchexec.tools.divine4”
Full name of tool module: “benchexec.tools.divine4”
Name of tool: “DIVINE”
Executable: “./divine”
Executable (absolute path): “/home/xstill/divine-svc/divine”
Version: “ 4.1.16+10a8a30b4db6”
…
```

Could you please paste here the output of `divine --version`? Sorry for the complications.

**Comment by vlstill** [comment]
I am sorry for my late reply. Sadly I am not able to reproduce this problem (using `benchexec` master, our verification submission and our faculty's machine with Ubuntu 18.04:
```
$ python3 -m benchexec.test_tool_info benchexec.tools.divine4
Name of tool module: “benchexec.tools.divine4”
Full name of tool module: “benchexec.tools.divine4”
Name of tool: “DIVINE”
Executable: “./divine”
Executable (absolute path): “/home/xstill/divine-svc/divine”
Version: “ 4.1.16+10a8a30b4db6”
…
```

Could you please paste here the output of `divine --version`? Sorry for the complications.

**Comment by vlstill** [comment]
I am sorry for my late reply. Sadly I am not able to reproduce this problem (using `benchexec` master, our verification submission and our faculty's machine with Ubuntu 18.04:
```
$ python3 -m benchexec.test_tool_info benchexec.tools.divine4
Name of tool module: “benchexec.tools.divine4”
Full name of tool module: “benchexec.tools.divine4”
Name of tool: “DIVINE”
Executable: “./divine”
Executable (absolute path): “/home/xstill/divine-svc/divine”
Version: “ 4.1.16+10a8a30b4db6”
…
```

Could you please paste here the output of `divine --version`? Sorry for the complications.

**Comment by vlstill** [comment]
I am sorry for my late reply. Sadly I am not able to reproduce this problem (using `benchexec` master, our verification submission and our faculty's machine with Ubuntu 18.04:
```
$ python3 -m benchexec.test_tool_info benchexec.tools.divine4
Name of tool module: “benchexec.tools.divine4”
Full name of tool module: “benchexec.tools.divine4”
Name of tool: “DIVINE”
Executable: “./divine”
Executable (absolute path): “/home/xstill/divine-svc/divine”
Version: “ 4.1.16+10a8a30b4db6”
…
```

Could you please paste here the output of `divine --version`? Sorry for the complications. Also, I had problem submitting this to github, so that is why I am replying later still.

**Comment by dbeyer** [comment]
./divine --version
./divine: relocation error: /localhome/dbeyer/RC-checkouts/SV-Competition/comp/bin-2019/divine-explicit/lib/libc.so.6: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

**Comment by vlstill** [comment]
Thank you very much. It seems that the build is somehow broken (probably due to the fact it was not built on Ubuntu, even though it passed my testing on Ubuntu 18.04), I have re-built it on Ubuntu and created a pull request in the verifiers repository: https://gitlab.com/sosy-lab/sv-comp/archives-2019/merge_requests/42. Hopefully it will work now.

**Pull request merged**
