### PR TITLE
Updating the Tracer-X submission

### PR DESCRIPTION
**Pull request by rasoolmaghareh**

### CODE REVIEW

**Comment by PhilippWendler** [comment]
This adds a new file in the wrong directory. Please correctly update the `benchexec/tools/tracerx.py` file. I suggest that you start with the current master branch and force-push to this PR.

**Comment by dbeyer** [comment]
@rasoolmaghareh Could you please apply your changes to the latest version from branch master?
You had put that file in a wrong folder and I later moved it after your changes were merged. You probably started with your own latest version. Should be easy to fix.

**Comment by dbeyer** [comment]
... and do you really want to keep all the debug print statements?

**Comment by rasoolmaghareh** [comment]
Let me fix the issue and push again.

**Pull request merged**
