### PR TITLE
Fix Ultimate tool-info

### PR DESCRIPTION
**Pull request by danieldietsch**
I made some stupid mistakes -- these commits fix the Ultimate tools.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
I see that `'-Xss4m'` is also added in the code further down, is it really intended to have it in both places?

**Comment by danieldietsch** [comment]
For versions it is not really necessary, but I wanted to have it for consistency. Further down it is necessary, because there we have to rebuild the string if someone specifies a memory limit.

**Comment by danieldietsch** [comment]
By the way, is it expected that benchexec converts ``memlimit="8GB"`` to ``8000000000`` bytes in ``rlimits`` ?
Thats whats happening in this line:
 https://github.com/sosy-lab/benchexec/blob/ec1a3193d16ff7279ebe5b42bf2e48dc82e6413f/benchexec/tools/ultimate.py#L215

**Comment by PhilippWendler** [comment]
Yes, benchexec handles the units for such parameters and converts them to bytes. This way tool-info modules do not need to care about supporting units in the user input.

**Comment by danieldietsch** [comment]
But 8GB (Gigabyte) are 8589934592 Byte, not 8000000000 Byte.

**Comment by PhilippWendler** [comment]
No, 8 GB (SI units) are 8000000000 Byte, 8 GiB are 8589934592 Byte. BenchExec always uses SI units as [documented](https://github.com/sosy-lab/benchexec/blob/master/doc/INDEX.md#units).

**Comment by danieldietsch** [comment]
Ok, got it. Then I use GiB.

**Pull request merged**
