### PR TITLE
Test suite optimization: Migrate test_cgroups.py and test_benchmark_definition.py to pytest

### PR DESCRIPTION
**Pull request by Naman-Priyadarshi**

### CODE REVIEW

**Comment by Naman-Priyadarshi** [comment]
@PhilippWendler Could you help me by explaining why the test is failing?

**Comment by PhilippWendler** [comment]
Well, `ModuleNotFoundError: No module named 'pytest'`. We have to add `pytest` as development dependency to `setup.cfg`, then it should be automatically installed in CI.

**Comment by PhilippWendler** [comment]
Yes, the CI config needs to be adapted to the migration as well.

**Comment by PhilippWendler** [comment]
Please merge the main branch into your branch, there is a required fix for a CI job on it (not related to your changes).

**Comment by PhilippWendler** [comment]
That's ok, don't worry. You could also cleanup the commits, rebase, and force-push, same effect in the end.

**Pull request closed without merging**
