### PR TITLE
Update ceagle.py

### PR DESCRIPTION
**Pull request by cgcgbcbc**
add additionalEnv: PATH

### CODE REVIEW

**Comment by dbeyer** [comment]
@cgcgbcbc Don't you want to write something like:
return {"additionalEnv": {"PATH": ":."}}

@PhilippWendler Can you please advice?

The extracted directories needs to be added to $PATH for Ceagle.

**Comment by PhilippWendler** [comment]
I agree, adding an executable to `PATH` won't work.

**Comment by PhilippWendler** [comment]
Though in general I advice against changing PATH in order to execute bundled tools like in this case.
It is generally trivial to ensure that scripts etc. call bundled tools from the correct directory instead of relying on PATH.

This has two advantages:
1. It makes it easier for users to run your tool, because they don't need to ensure PATH is correct all the time.
2. It ensures that actually the bundled tool gets executed, and not some other binary with the same name that happens to be installed on the system.

**Comment by cgcgbcbc** [comment]
@dbeyer Thanks for pointing out! I've fixed it. It's strange that it works when I write that way.

@PhilippWendler Thank you for your advice! I'll figure out how to find the binary's location even when current working directory is outside the binary's location. Can we make this as a walkaround before we improve our tool?

**Comment by cgcgbcbc** [comment]
@PhilippWendler Finally I found the solution to this problem. Now whether call the bundled tools from PATH or not (i.e. called with a relative/absolute  path pointing to the file) does not matter now. Should I then remove what this pr added?

**Comment by dbeyer** [comment]
@PhilippWendler Your advice should be conserved in an FAQ or so.  What would be a good place for where to have that?

**Pull request merged**
