### PR TITLE
Double the score if a validator refutes or confirms a wrong witness

### PR DESCRIPTION
**Pull request by dbeyer**
ATTENTION: Do not squash because the commits are referenced in competition artifacts.

SV-COMP 2023 scoring schema is extended to double the score if a validator refutes or confirms a wrong witness.

Reference: https://doi.org/10.1007/978-3-031-22308-2_8 (page 171, last paragraph)

### CODE REVIEW

**Comment by PhilippWendler** [comment]
There is a note warning that the commit hashes are important, but there are several force pushes to this branch. Is this intended and the current set of hashes the desired one?

**Comment by dbeyer** [comment]
> There is a note warning that the commit hashes are important, but there are several force pushes to this branch. Is this intended and the current set of hashes the desired one?

First I thought that it is ugly to show others how I found my way to the final implementation of this, and I force-pushed.

But then I realized that I had ran experiments for SV-COMP that now have those intermediate commit hashes in the provenance section of the results XML files, and thus, I restored the history. It would be super-ugly for reproducibility if the SV-COMP results point to commit hashes that do not exist in the history of any branch or tag.

**Comment by PhilippWendler** [comment]
Current state looks really nice! Would be fine to merge for me from a conceptual point of view.

**Comment by dbeyer** [comment]
The corresponding change in the results post-processing are here:
https://gitlab.com/sosy-lab/benchmarking/competition-scripts/-/commit/8f0f55c3e9b772e11c89e396105136d5a7fcdff3

**Review by PhilippWendler — APPROVED** [review]

**Comment by PhilippWendler** [comment]
Ready to merge for me, for you as well?

**Comment by dbeyer** [comment]
Yes, ready to merge.

**Pull request merged**
