### PR TITLE
doc: Add NixOS to `INSTALL.md`

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
I am currently working on a NixOS module for BenchExec, stay tuned.

See: https://github.com/NixOS/nixpkgs/pull/263375

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Nice! I won't be able to help with the NixOS side, but if you have any other questions, I would be glad to assist.

**Comment by lorenzleutgeb** [comment]
The systemd unit file you and the docs on the cgroups setup you provide are very helpful already, thank you! If I run into issues, I'll contact you!

**Comment by lorenzleutgeb** [comment]
Downstream pull request https://github.com/NixOS/nixpkgs/pull/263375 was merged. This means that the options mentioned in this PR are available in the "unstable" rolling release of NixOS shortly. Also, it was merged just in time for the NixOS 24.05 branch-off (see [Release Schedule](https://github.com/NixOS/nixpkgs/issues/303285)), which means that BenchExec and friends will appear in the stable release NixOS 24.05.

I don't see a big issue in the fact that the changes in this PR mention 24.05, because it will be released within a few weeks, and this PR still needs review.

**Review by PhilippWendler — APPROVED** [review]

**Comment by PhilippWendler** [comment]
Just to make sure, this is ready to merge from your point of view? Then I will do so.

**Comment by lorenzleutgeb** [comment]
Just resolved the conflict with #1038 but good to merge from my side, yes!

**Comment by lorenzleutgeb** [comment]
Side note: If you get reports about issues with the packages in Nixpkgs or NixOS modules (also for cpu-energy-meter and pqos_wrapper) feel free to ping me. I cannot guarantee any service level but am planning to maintain those on a best-efforr basis.

**Pull request merged**
