### PR TITLE
Update Verifuzz.py for versioning

### PR DESCRIPTION
**Pull request by animeshbchowdhury**

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Thanks. 

While you are at it, you might want to consider adding documentation as [suggested here](https://github.com/sosy-lab/benchexec/commit/bd82323567b2c8ebade40b8778460de1dda53308#diff-564acd0f58dd345e8d161cb791d6af53). Would be great. An example is [here](https://github.com/sosy-lab/benchexec/blob/bd82323567b2c8ebade40b8778460de1dda53308/benchexec/tools/cpachecker.py).

**Comment by PhilippWendler** [comment]
Doesn't your tool output something like `Verifuzz 1.0.0` on stderr? Please make sure that the `version` method returns only the version number.
Please [test](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md#testing-the-tool-integration) the tool-info module!

**Comment by animeshbchowdhury** [comment]
Yes. I changed it just now. Version number will show "1.0.0" instead of "Verifuzz 1.0.0". Because, of the same the build was not going through CI checks in SVCOMP submission.

**Comment by animeshbchowdhury** [comment]
Hi,

@PhilippWendler , I have tested it on my end. The tool-info module is working properly with this change on our tool.

Thanks,
Animesh

**Comment by animeshbchowdhury** [comment]
`Name of tool module: “benchexec.tools.verifuzz”
Full name of tool module: “benchexec.tools.verifuzz”
Documentation of tool module:
	VeriFuzz
Name of tool: “VeriFuzz”
Executable: “./scripts/verifuzz.py”
Executable (absolute path): “/home/animesh/svcompbench/verifuzz/scripts/verifuzz.py”
Version: “1.0.0”
Working directory: “.”
Working directory (absolute path): “/home/animesh/svcompbench/verifuzz”
Program files:
	“lib”
	“exp-in”
	“fuzzEngine”
	“scripts”
	“supportFiles”
	“prism”
	“bin”
	“jars”
Program files (absolute paths):
	“/home/animesh/svcompbench/verifuzz/lib”
	“/home/animesh/svcompbench/verifuzz/exp-in”
	“/home/animesh/svcompbench/verifuzz/fuzzEngine”
	“/home/animesh/svcompbench/verifuzz/scripts”
	“/home/animesh/svcompbench/verifuzz/supportFiles”
	“/home/animesh/svcompbench/verifuzz/prism”
	“/home/animesh/svcompbench/verifuzz/bin”
	“/home/animesh/svcompbench/verifuzz/jars”
Minimal command line:
	“['scripts/verifuzz.py', 'INPUT.FILE']”
Command line with parameter:
	“['scripts/verifuzz.py', '-SOME_OPTION', 'INPUT.FILE']”
Command line with property file:
	“['scripts/verifuzz.py', '--propertyFile', 'PROPERTY.PRP', 'INPUT.FILE']”
Command line with multiple input files:
	“['scripts/verifuzz.py', 'INPUT1.FILE', 'INPUT2.FILE']”
Command line CPU-time limit:
	“['scripts/verifuzz.py', 'INPUT.FILE']”`

**Comment by dbeyer** [comment]
Looks good now.  I will merge now.

Please remember to put the documentation, as Philipp suggested.

**Comment by animeshbchowdhury** [comment]
@dbeyer , Sure. I will put the documentation as suggested.

**Pull request merged**
