### PR TITLE
added new command line argument -ultimatedata to ultimate

### PR DESCRIPTION
**Pull request by danieldietsch**

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Thanks!

Do older versions of Ultimate support this as well, or will they at least ignore it?

**Comment by danieldietsch** [comment]
They should ignore it. But I can try and make another version check and only supply it for newer versions.

**Comment by PhilippWendler** [comment]
If they ignore it then its fine for me.

**Comment by danieldietsch** [comment]
Now it should also work for all the older versions.

**Pull request merged**
