### PR TITLE
back button added

### PR DESCRIPTION
**Pull request by kalpit4088**
fixes    https://github.com/sosy-lab/benchexec/issues/113

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Thanks for your contribution!

It seems that this doesn't address #113 though, right? #113 is about making the "back" button of the browser have an effect, this adds a new back button in the table. Is this intentional? Do you think it is worth having this additional button? Users can already close the modal for example by clicking somewhere on the background outside of it.

**Comment by kalpit4088** [comment]
I don't think that we can do that (making the "back" button of the browser have an effect). This is the article which I read [https://forums.asp.net/t/1882709.aspx?how+to+enable+back+button+of+browser](url) . It says that back button of browser remains enable by default. I think the reason why we can't use back button of browser using "window.history.back()" because url is not changing when we open/close html overlay. Hence I thought to create the back button.

**Comment by kalpit4088** [comment]
@PhilippWendler I am open to any other suggestions on anything that can be done.

**Comment by PhilippWendler** [comment]
This forum discussion seems quite old. I have read [here](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) (which is linked from the issue) that it should be possible what is described in #113. Or do you have any information about why this technique is not usable for what we would need?

**Comment by PhilippWendler** [comment]
Please do not mix unrelated features in the same PR.

Are you planning on updating this PR with a new fix for #113? Otherwise I would close this PR.

**Comment by kalpit4088** [comment]
I am working on enhancement part and will make an update soon. So I am closing this Pull Request.

**Pull request closed without merging**
