### PR TITLE
removed required path from various tools

### PR DESCRIPTION
**Pull request by skanav**
PR to remove the variable `REQUIRED_PATH` from various tool info modules.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
The response in #698 was quite negative (in favor of keeping `REQUIRED_PATHS`), so why remove this now?

**Comment by dbeyer** [comment]
But the PR does not touch tool-info modules of users that use the `REQUIRED_PATHS` (cf. #698).

The `REQUIRED_PATHS` that are touched in this PR are not tested and most likely contain omissions, as we witnessed incidentally after many weeks (years?) for Symbiotic in #699.

**Comment by PhilippWendler** [comment]
@lembergerth @MartinSpiessl @gernst Could you please check whether this PR removes `REQUIRED_PATHS` from any tool-info module where you find it useful for you? Please tell us, then we would keep these and remove only the remaining.

**Review by lembergerth — APPROVED** [review]
Looks good to me. I sporadically use cbmc and klee in the VCloud, but I can put the result files in a parent directory.

**Comment by gernst** [comment]
Looks good to me, too, my tools are unaffected. Do I understand correctly: the default is `REQUIRED_PATHS=["."]`?

**Comment by PhilippWendler** [comment]
No, the default is just the `executable`. So at least it would not match lots of useless stuff.

**Comment by lembergerth** [comment]
@gernst The workaround would be to use `benchmark.py` with something like the following: `--cloudAdditionalFiles lib/ bin/ src/`

**Comment by gernst** [comment]
Uh, what's the use case in which the default actually works? Almost all tools do have more than one required file. Just curious - feel free to ignore me.

**Comment by PhilippWendler** [comment]
Yes, but there is no better default. As discussed in #698, `.` is not a good default and would still fail for many tools (those with the executable in a subdirectory, for example).

**Review by gernst — APPROVED** [review]

**Review by MartinSpiessl — APPROVED** [review]
Looks good to me.
None of "my" tools I use is affected.

**Pull request merged**
