### PR TITLE
update BRICK tool-info

### PR DESCRIPTION
**Pull request by brick-tool-dev**
add environment variable

### CODE REVIEW

**Comment by PhilippWendler** [comment]
While it is possible to do what is suggested in this PR, this would mean that executing your tool manually would be tricky for users. If they just use a command line as copied from the tool logs, it will fail, probably with an error message that is not helpful.

Don't you think it would make your tool more user-friendly if it set this environment variable internally, e.g., in a wrapper script?

**Comment by brick-tool-dev** [comment]
Hi,
actually this environment variable is needed before trying to set it internally.
If I don't add LD_LIBRARY_PATH, it can't run to set it.

Can I merge it first and find a better solution later?

**Comment by dbeyer** [comment]
It would be nicer to the users (and me) if you had a wrapper script that sets the variable and then starts the actual tool.

In the log files, the first line is the command line and it is convenient for reproducing results to be able to simply copy & paste the command line.

**Comment by brick-tool-dev** [comment]
Hi, I have written a wrapper script and uploaded a new zip to [archives-2020](https://gitlab.com/sosy-lab/sv-comp/archives-2020/merge_requests/95).
Can I ask a new run to check whether it can run properly?
A time limit of 60s will be enough to see whether the script can work.

**Comment by PhilippWendler** [comment]
Is this still relevant?

**Comment by dbeyer** [comment]
According to the latest benchmark of BRICK in the context of SV-COMP,
using the new archive, the new wrapper script works well.

@PhilippWendler I suggest to close this issue.

@brick-tool-dev Could you please confirm?

**Comment by brick-tool-dev** [comment]
Hi, the warpper script works properly. So it's nice to close this pr. Thanks so much!

**Pull request closed without merging**
