### PR TITLE
update TI - predatorHP - removed use of stderr in get version

### PR DESCRIPTION
**Pull request by skanav**
update tool info module of predatorHP

### CODE REVIEW

**Comment by PhilippWendler** [comment]
I guess this would break backwards compatibility with older tool versions?

@versokova Is there a way to get the version that is compatible with all tool versions?

If not, I guess we could try a fallback solution.

**Comment by skanav** [comment]
I am surprised that it worked before. version is printed on `stdout` and `stderr` is empty. That is causing the version number to be `empty`.

**Comment by versokova** [comment]
@skanav I am pretty sure that the version is printed on `stderr`. See [code](https://github.com/versokova/predatorhp/blob/master/predatorHP.py#L108).

**Comment by skanav** [comment]
> @skanav I am pretty sure that the version is printed on `stderr`. See [code](https://github.com/versokova/predatorhp/blob/master/predatorHP.py#L108).

yes, thanks for the clarification. It seems that it prints on `stdout` in python3 and `stderr` in python2.

**Comment by skanav** [comment]
Closing the PR as the CI in verifier archives passed after adding packages `python2`and `python-is-python2` to `Dockerfile.user`.

For reference:
https://gitlab.com/sosy-lab/sv-comp/archives-2021/-/merge_requests/60
https://gitlab.com/sosy-lab/sv-comp/archives-2021/-/merge_requests/58

**Pull request closed without merging**
