### PR TITLE
fixes lazy load of js library like JQPlot.

### PR DESCRIPTION
**Pull request by kalpit4088**
fixes https://github.com/sosy-lab/benchexec/issues/123

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Thanks for your submission!

Unfortunately, this PR contains code related to some other feature, please remove this.

Also, it breaks the [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) that we have been using, this should be avoided.

Could you please explain a little bit more how your chosen approach of lazy loading works? Does it work in all browsers? Would it also be possible by a more modern approach such as declaring the scripts as `async`, or would that have other disadvantages?

**Comment by kalpit4088** [comment]
I am working on enhancement part and will make an update soon. So I am closing this Pull Request.

**Comment by kalpit4088** [comment]
This approach works similarly as it works with "async" attribute, The only difference is that the async attribute works fine on modern browsers – supported by Firefox 3.6+, IE 10+, Chrome 2+, Safari 5+, iOS 5+, Android 3+, however  for a deeper browser support the script I wrote works perfectly. So yeah the way I have used "async" method works for all browsers.

**Comment by kalpit4088** [comment]
I think I've put subresource integrity part inside every script tag. But if it doesn't work then pls let me know I'll fix this too.

**Pull request closed without merging**
