### PR TITLE
DuanZhaoInterpchecker

### PR DESCRIPTION
**Pull request by duanzhao-dz**
update interpchecker.py tool module

### CODE REVIEW

**Comment by PhilippWendler** [comment]
What is the difference between this and CPAchecker's module?

**Comment by duanzhao-dz** [comment]
Our tools is based on CPAChecker and does not change the command line of CPAChecker. Now, we are testing our tool using the tool module of cpachecker

**Comment by PhilippWendler** [comment]
What's the result? Can this be closed?

**Comment by dbeyer** [comment]
@duanzhao-dz Can we close the pull request?

**Comment by duanzhao-dz** [comment]
Yes, you can close the pull request.  I will send a new pull request to you.

**Pull request closed without merging**
