### PR TITLE
Remove object state for MetaVal tool-info module

### PR DESCRIPTION
**Pull request by lembergerth**
Currently, the MetaVal tool-info module is stateful: It only imports required (sub-)tool-info modules when constructing the commandline (`cmdline`), stores it in an object attribute `self.wrappedTools` and then reuses that for `determine_result`.

This means that `determine_result` will not work if `cmdline` was not executed on the same Tool-object before.

This PR changes that:  
Do not keep a state in MetaVal tool-info module,
but just load the required tool-info module of used components
when cmdline and result are determined.

@MartinSpiessl As the maintainer of MetaVal, does this PR make sense to you?

### CODE REVIEW

**Comment by MartinSpiessl** [comment]
Sure, this doesn't reduce the functionality, only extends it. Probably at the cost of some performance (constructing Tool objects for each run?).

Why can't we have both, i.e., keep the caching as such and load the module on a cache miss?

**Comment by lembergerth** [comment]
Thanks for looking at it!

> Why can't we have both, i.e., keep the caching as such and load the module on a cache miss?

Sure, I don't mind - it will *slightly* complicate the code, though. Does creating a `Tool`-object really involve any measurable performance penalty compared to a cache lookup?

**Comment by PhilippWendler** [comment]
Note that the current state of this PR will break tool-info modules that expect that what is documented in BenchExec is always followed: first the methods that return general information about the tool are called, then the run-specific methods. While there is no explicit guarantee that methods like `executable()` are always called, several tool-info modules assume that, and if we change anything in this regard I would rather add this explicit guarantee instead of explicitly ruling it out.

Furthermore, by the same guarantees this kind of caching is safe, and I see no reason to change this and further complicate this (already quite complex) tool-info module.

**Comment by lembergerth** [comment]
Why do you feel this PR makes the module more complicated? It removes state and duplicate code, so isn’t it a simplification?

And which behaviour will break? It seems I missed something important 😬 

> I would rather add this explicit guarantee instead of explicitly ruling it out.

This would make the reuse of benchexec tool-info modules more complicated per se (they were/are used by tbf, symbiotic and CoVeriTeam, at least), but it would also make handling any existing bugs due to state more straightforward - so that would be awesome.

**Comment by PhilippWendler** [comment]
> Why do you feel this PR makes the module more complicated? It removes state and duplicate code, so isn’t it a simplification?

After fixing the broken behavior, the code will be necessarily more complex than before.

> And which behaviour will break? It seems I missed something important :grimacing:

Any tool-info module that stores state after detecting the executable or the version of the tool and needs this state for `determine_result` will be broken.

> > I would rather add this explicit guarantee instead of explicitly ruling it out.
> 
> This would make the reuse of benchexec tool-info modules more complicated per se (they were/are used by tbf, symbiotic and CoVeriTeam, at least), but it would also make handling any existing bugs due to state more straightforward - so that would be awesome.

Done in a77c6c5c.

**Comment by lembergerth** [comment]
Took me a while, but now I understand - the issue with this PR is that I create new `Tool`-objects, so no state is stored between `executable` and `determine_result` for the sub-tools.

Thanks for clarifying the documentation so fast!

**Pull request closed without merging**
