### PR TITLE
Add tool info for validator Witch

### PR DESCRIPTION
**Pull request by ayazip**
Add tool info for YAML violation witness validator Witch

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Can't you use https://github.com/sosy-lab/benchexec/blob/main/benchexec/tools/symbiotic-witch.py?

**Comment by ayazip** [comment]
@PhilippWendler 
I could, but I am not sure how to then specify that  Witch should use this module. The verifiers have this info in the fm-tools repository, but the validators don't have this. 

I guess that it would it be enough to put "symbiotic-witch" as the tool name in the benchmark definition file for Witch, but I am not sure. Please confirm that this is the case; if it is, I will change it and close this PR.

**Comment by PhilippWendler** [comment]
> @PhilippWendler I could, but I am not sure how to then specify that Witch should use this module. The verifiers have this info in the fm-tools repository, but the validators don't have this.

For questions about the FM-Tools-Repository, please ask there. But AFAIK know a tool listed there can point to its tool-info module with the `benchexec_toolinfo_module` key. For example, CPAchecker does so (and it is both a verifier and a validator).

> I guess that it would it be enough to put "symbiotic-witch" as the tool name in the benchmark definition file for Witch, but I am not sure. Please confirm that this is the case; if it is, I will change it and close this PR.

The `tool` attribute of the `benchmark` tag in the benchmark definition determines which tool-info module BenchExec uses, yes.

**Comment by ayazip** [comment]
Great, thanks!

**Pull request closed without merging**
