### PR TITLE
lazyload js problem resolved

### LINKED ISSUE #123: Lazy-load JavaScript libraries where possible
The HTML tables produced by `table-generator` include several libraries like JQPlot and zip.js that are only sometimes necessary. These could be loaded on demand to reduce the initial loading time of the table.

### PR DESCRIPTION
**Pull request by kalpit4088**
fixes #123

### CODE REVIEW

**Comment by kalpit4088** [comment]
This approach works similarly as it works with "async" attribute, The only difference is that the async attribute works fine on modern browsers – supported by Firefox 3.6+, IE 10+, Chrome 2+, Safari 5+, iOS 5+, Android 3+, however for a deeper browser support the script I wrote works perfectly. So yeah the way I have used "async" method works for all browsers.

**Comment by kalpit4088** [comment]
@PhilippWendler  I think I've put sub-resource integrity part inside every script tag. But if it doesn't work then please let me know I'll fix this too.

**Comment by PhilippWendler** [comment]
We can ignore all older browsers than the ones you have listed, so I would prefer the simpler solution that works only in these browsers.

I cannot understand how the subresource-integrity should work in your code. How would the browser now that it should check the hash of the loaded scripts? Did you test it by changing the hash and verifying that the script indeed fails to load?

**Comment by kalpit4088** [comment]
@PhilippWendler  okay so i'll do it with that way. So that subresource-integrity can also work.

**Comment by PhilippWendler** [comment]
I just noticed now that this PR attempts to update the example table in the gh-pages branch, which is auto-generated. PRs need to be made for the template in the master branch.

**Pull request closed without merging**
