### PR TITLE
Rename JPF to SPF

### PR DESCRIPTION
**Pull request by peterschrammel**
JPF is now JPF-core. Therefore it makes more sense to call the symbolic version SPF.

### CODE REVIEW

**Comment by peterschrammel** [comment]
@dbeyer, this one would be required to run SPF.

**Comment by PhilippWendler** [comment]
How does this relate to #324?

(Note that for SV-COMP, if you submit a tool twice in two different configurations, you should not add two tool-info modules to BenchExec, just one. Tool-info modules should only be added for separate tools.)

**Comment by peterschrammel** [comment]
To resolve the confusion:
- Initially, I created a jpf.py for the SPF tool (symbolic execution version of JPF)
- Then Cyrille also wanted to submit the 'plain' version of JPF that he called JPF-core.
- Then we came to the conclusion that this is confusing and jpf.py should be renamed spf.py

So, these are _different_ tool variants (_more_ than just different configurations).

jpf-core.py could inherit from spf.py or vice versa. This is doable.

**Comment by peterschrammel** [comment]
To resolve the confusion:
- Initially, I created a jpf.py for the SPF tool (symbolic execution version of JPF)
- Then Cyrille also wanted to submit the 'plain' version of JPF that he called JPF-core.
- Then we came to the conclusion that this is confusing and jpf.py should be renamed spf.py

So, these are _different_ tool variants (_more_ than just different configurations).

jpf-core.py could inherit from spf.py or vice versa. This is doable.

**Comment by peterschrammel** [comment]
To resolve the confusion:
- Initially, I created a jpf.py for the SPF tool (symbolic execution version of JPF)
- Then Cyrille also wanted to submit the 'plain' version of JPF that he called JPF-core.
- Then we came to the conclusion that this is confusing and jpf.py should be renamed spf.py

So, these are _different_ tool variants (_more_ than just different configurations).

jpf-core.py could inherit from spf.py or vice versa. This is doable.

**Comment by peterschrammel** [comment]
To resolve the confusion:
- Initially, I created a jpf.py for the SPF tool (symbolic execution version of JPF)
- Then Cyrille also wanted to submit the 'plain' version of JPF that he called JPF-core.
- Then we came to the conclusion that this is confusing and jpf.py should be renamed spf.py

So, these are _different_ tool variants (_more_ than just different configurations).

jpf-core.py could inherit from spf.py or vice versa. This is doable.

**Pull request merged**
