### PR TITLE
added possibility to wrote stdout and stderr to different files

### PR DESCRIPTION
**Pull request by jwacalex**
added two parameters for writing stdout and/or stderr to different paths and not merge them to a generic output.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
This pull request mixes output file writing with sudo args, could you please clean this up?

Also, why 3 files instead of just 2?

**Comment by jwacalex** [comment]
#104 was splitted because I do not want to mix up both requests as one in upstream. if you want both changes we will create a new request which combines them.

it writes three files, one for stdout one for stderr and the still existing output log which might contain more information besides the pure stdout/err

**Comment by PhilippWendler** [comment]
Each of the pull requests should add exactly one feature, so please clean up this pull request.

I don't really see the need for the the three files, but if you prefer this I think this is ok.
Please move their whole setup to the utility function, though, to avoid making the main function any longer than necessary.

Tests for this functionality would be good, too.

**Comment by jwacalex** [comment]
regarding the pull requests the intention was to have them splitted but I broke something while creating them and merging too much commits.

**Comment by jwacalex** [comment]
closing this request, because repository needs a clean-up due to some messy advent calendar fixes. there will be a new request from the current master

**Pull request closed without merging**
