### PR TITLE
Test suite optimization: Migrate test_cgroups.py and test_benchmark_definition.py to pytest

### PR DESCRIPTION
**Pull request by Naman-Priyadarshi**

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Ah, I forgot to mention: Can you please push to a branch in this repository and then create a PR from it? This way our CI will work. Please use a more descriptive branch name than `migration_1` in this case.

**Comment by Naman-Priyadarshi** [comment]
yes okay, will push to a different branch. Could you help me suggest a new descriptive branch name? Thank you

**Comment by Naman-Priyadarshi** [comment]
Which branch should I push my changes to? As I don't have permissions to create a new branch

**Comment by Naman-Priyadarshi** [comment]
oh sorry! must've missed the email

**Pull request closed without merging**
