### PR TITLE
Use regex to insert urls into yaml-files in overlay-window.

### PR DESCRIPTION
**Pull request by kfriedberger**
see #402.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
> Under the assumption that yaml-files are nice,

Where does this assumption come from? Users can write all kinds of YAML files and use them with BenchExec.

A regexp-based solution does not even work with "nice" YAML files if they specify several input files, and such task definitions are already commonly in use (e.g., in SV-COMP).

**Comment by kfriedberger** [comment]
In my opinion, the regex-based solution works for 95% of all existing tables.
If the regex does not match, we will not add any url, which is exactly the situation right now. Thus the solution is a safe intermediate base until someone adds a yaml-parser-based solution.

Most users work with yaml files consisting of single C-files and single properties (all from sv-benchmark repository). Just take a look at tables from CPAchecker's buildbot (except Java) and all categories of SV-COMP (except Java) and maybe also TestComp.

I am not finishing #419, but just starting (with one step/a few lines of code that handle most of the existing applications). What needs to be done for this PR to get merged soon?

**Comment by PhilippWendler** [comment]
Adding a feature that silently does not work in some circumstances, or works only partially, is highly confusing to users and a bad user experience. We do not want to disappoint BenchExec's users in such ways.

Such a hack would only be acceptable if a full solution would be impossible or too difficult to implement, but this is not the case for #402.

**Comment by PhilippWendler** [comment]
This conflicts with the ongoing development in branch `react-table`, which will be merged soon, thus it does not make sense to merge this PR.

**Pull request closed without merging**
