### PR TITLE
#483: implement hash routing

### PR DESCRIPTION
**Pull request by DennisSimon**
Hi @PhilippWendler 

Here is my PR for the implementation of hash routing as suggested in #483 . 

This PR removes the `react-tabs` dependency and implements `react-router` for routing. 

Added functionality: 

- Navigate to any page via hash-routing (e.g. `localhost/#/table`) 
- Every change to default configurations of graphs will be reflected in the URL using query parameters. 
This URL is also used to configure the graphs with the settings provided in the query parameters on load. 

Looking forward to  your feedback :)

### CODE REVIEW

**Comment by DennisSimon** [comment]
Hi @PhilippWendler 
I rebased to master and incorporated your comments into the code. 
About the Hash Routing not working on Chromium:  I don't know too much about that sadly, it should work and it does work on Chrome. So it's likely something that is browser specific and is hopefully fixed soon.

**Comment by PhilippWendler** [comment]
I noticed that when I open a plot, copy the URL and then open it in a new tab, not all settings that are in the URL are applied. It seems to affect at least the plot type (direct/quantile) and the correct/all results toggle (for both scatter and quantile plots), for reference here are some URLs for testing:
- http://127.0.0.1:3000/#/quantile?column=walltime&quantile=false&linear=true&correct=false
- http://127.0.0.1:3000/#/scatter?toolX=0&columnX=walltime&toolY=0&columnY=memUsage&line=5&linear=true&correct=false

Could you please check that all URL settings are applied (maybe I forgot to test some)?

It is ok for now if some settings are not stored in the URL (e.g., all the layout settings of the table tab), but those that are stored in the URL should be applied on load, otherwise this is confusing for experienced users.

**Comment by DennisSimon** [comment]
> I noticed that when I open a plot, copy the URL and then open it in a new tab, not all settings that are in the URL are applied. It seems to affect at least the plot type (direct/quantile) and the correct/all results toggle (for both scatter and quantile plots), for reference here are some URLs for testing:
> 

They should be applied on load. 
I will take a look

**Comment by PhilippWendler** [comment]
Now the defaults are wrong again?

**Pull request merged**
